apiVersion: v1
kind: ConfigMap
metadata:
  name: localstack-config
data:
  create-queues.sh: |
      #!/bin/bash
      aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name notification_queue

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack-dev
          image: localstack/localstack
          ports:
            - containerPort: 4566
          env:
            - name: SERVICES
              value: "sqs"  # Include SQS service in LocalStack
        - name: awscli
          image: amazon/aws-cli
          command: ["/bin/bash"]
          args: ["-c", "cat /tmp/create-queues.sh > create-queues.sh && ls && chmod +x create-queues.sh && ./create-queues.sh && sleep infinity"]
          # args: ["-c", "echo \"$CREATE_QUEUES_SCRIPT\" > /tmp/create-queues.sh && chmod +x /tmp/create-queues.sh && /tmp/create-queues.sh"]
          env:
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_ACCESS_KEY_ID
              value: LOCAL
            - name: AWS_SECRET_ACCESS_KEY
              value: LOCAL
          volumeMounts:
            - name: localstack-config
              mountPath: /tmp
      # initContainers:
      volumes:
        - name: localstack-config
          configMap:
            name: localstack-config
---
apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-localstack-svc
spec:
  ports:
    - protocol: TCP
      port: 4566
      targetPort: 4566
  selector:
    app: localstack
